# install and configure Nginx
- name: ensure Nginx is installed
  apt: name=nginx state=present update_cache=yes
  become: yes

- name: write custom Nginx configuration
  template: src=nginx_conf.j2
            dest=/etc/nginx/conf.d/app.conf
  become: yes

