# install and configure Nginx
- name: ensure Nginx is installed
  apt: name=nginx state=present update_cache=yes
  become: yes

- name: ensure Lets Encrypt is installed
  apt: name=letsencrypt state=present update_cache=yes
  become: yes

- name: write custom Nginx configuration
  template: src=nginx_conf.j2
            dest=/etc/nginx/conf.d/{{ app_name }}.conf
  become: yes
  notify:
    - restart nginx

- name: create Lets Encrypt directory
  file: name=/var/www/letsencrypt state=directory
  become: yes

- name: remove default Nginx configuration
  file: name=/etc/nginx/sites-enabled/default state=absent
  become: yes


- name: check if certificate already created
  stat:
    path: "/etc/letsencrypt/live/{{ fqdn }}"
  register: certs
  become: yes

- name: stop nginx to obtain Lets Encrypt certificate
  service:
    name: nginx
    state: stopped
  become: yes
  when: not certs.stat.exists

- name: create certificate with Lets Encrypt command
  shell: "letsencrypt certonly --standalone -d {{ fqdn }} -w {{ web_serve_dir }} -m {{ ssl_cert_email }} --agree-tos --renew-by-default --non-interactive"
  become: yes
  when: not certs.stat.exists

- name: generate strong Diffie-Hellman group
  shell: "openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048"
  become: yes
  when: not certs.stat.exists 

- name: start nginx back after Lets Encrypt cert obtained
  service:
    name: nginx
    state: started
  become: yes
  when: not certs.stat.exists 
